# Generated by Django 5.0.3 on 2024-03-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='travelPoints',
            field=models.FloatField(default=0.0),
        ),
    ]
