# Generated by Django 5.0.3 on 2024-03-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_passenger_travelpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='travelPoints',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
