version: "3.8"
services:
    api:
        build:
            context: .
        image: django-api
        environment:
            DB_USER: "[USERNAME]""
            DB_PWD: "[your_password]"
            DB_HOST: [HOST]
            DB_PORT: "[PORT_NUMBER]""
            DB_NAME: "[DB_NAME]""
        volumes:
            - ./:/app/
        ports:
            - "80:5000"
        depends_on:
            - postgres
    postgres:
        image: postgres:13.6
        restart: always
        ports:
            - "[YOUR_PORT]:5432"
        environment:
            - POSTGRES_USER=[USERNAME]
            - POSTGRES_PASSWORD=[your_password]
